* Touchpad
I encountered only two issues: too fast and sensitive scrolling and
palm detection. This laptop has a large touchpad and withouth a proper
palm detection it can make typing very frustrating. Normally, the palm
detection shouldn't be an issue unless you use =synaptics= drivers.
AFAIK, by default Xubuntu 24 will use =libinput= and this shouldn't be
a problem for most. I solved both my issues with =libinput=.

1. Check whether libinput is driving your touch pad:

#+begin_src shell
grep -e "Using input driver 'libinput'" /var/log/Xorg.0.log
#+end_src

If touch pad is not listed there, then follow instructions for setting
up =libinput= here:
https://wiki.archlinux.org/title/Libinput

2. Change scroll speed/sensitivity with
   
#+begin_src shell
xinput set-prop 9 "libinput Scrolling Pixel Distance" 40
#+end_src

Use lower than 40 if it is too slow for you. Assuming that =9= is the
ID of your touch pad. To learn the id, use:

#+begin_src shell
xinput list
#+end_src

3. To make the change permanent, edit:
   =/usr/share/X11/xorg.conf.d/40-libinput.conf=.

Find an etry for touchpad catchall and add a line =Option
"ScrollPixelDistance" "40"=. Example:

#+begin_src shell
Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "ScrollPixelDistance" "40"
EndSection
#+end_src

Source: https://forums.linuxmint.com/viewtopic.php?t=412052 

* Xfce and UI
The screen on this laptop is HiDPI. Most likely, the UI and text will
look too small. Here is what helped me to make it more legible.

1. Set window scaling to =2=.

   Run =Xfc4-apperance-settings=, open "Settings" tab. Set window
   scaling to =2x=.

2. Set font DPI to =80=.

   In =Xfc4-apperance-settings=, open "Fonts" tab. Set "Custom DPI
   setting" to =80=. Test smaller and larger DPI values to find the
   what works best for you.

Source:
https://old.reddit.com/r/xfce/comments/x98vk7/1x_scale_too_small_but_2x_scale_too_large_on_14/

Optional: consider a HiDPI compatible theme for Xfce in
=Xfc4-apperance-settings=. One example is =Greybird= (shipped by
default).

3. Install both =qt5ct= and =qt6ct=.

   Applications using QT for their GUI will not obey the sessings you
   set up above. You can controll UI of these applications via =qt5ct=
   and =qt6ct=. Unfortunately, you have to have both because there is
   no application able to control both versions of QT.

   #+begin_src shell
     sudo apt update
     sudo apt install qt5ct qt6ct -y
   #+end_src

To make them work properly, you have to set environment variable
=QT_QPA_PLATFORMTHEME= to =qt5ct=. You set in
=/etc/X11/Xsession.d/56xubuntu-session=.

Source:
https://askubuntu.com/questions/1398554/unable-to-change-qt-qpa-platformtheme-environment-variable

In both =qt5ct= and =qt6ct=, change =style= to =gtk2= in the
"Appearance" tab. In the "Fonts" tab, increase font size to what works
for you. Right now, =20= works well for me.

* Solution to the black screen after closing the lid:

If you have this issue, follow rchfox's solution here:
https://forums.debian.net/viewtopic.php?t=160518

* Coonecting a bluetooth headset
You might get problems connecting a headset via bluetooth. The issue
is likely with =pulseaudio=. Remove it and use =pipewire= as discussed
here:
https://askubuntu.com/questions/1479606/bluetooth-br-connection-profile-unavailable-issue-on-upgrade-to-xubuntu-23-04


* Unstable WiFi connection during video conferencing
In =/etc/NetworkManager/conf.d/default-wifi-powersave-on.conf= change
=wifi.powersave= to =2=. Like this:

#+begin_src shell
[connection]
wifi.powersave = 2
#+end_src
